// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJqqXnT4j1uI1vvtZioeYhO2ELciiGz5A',
    appId: '1:125898760820:web:2176102aafcc3ea6602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    authDomain: 'book-list-ebb15.firebaseapp.com',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
    measurementId: 'G-8GWZ5JZ7PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRrVDI8TkZoojU84-qaR9A__dGdNReKo',
    appId: '1:125898760820:android:845b6b4d3f7ad410602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTJJn_t5DQJn-JyMR7Bo6oRMiZxo42jI',
    appId: '1:125898760820:ios:c5093559c529e1df602721',
    messagingSenderId: '125898760820',
    projectId: 'book-list-ebb15',
    storageBucket: 'book-list-ebb15.firebasestorage.app',
    iosClientId: '125898760820-j0sgebbbrks43f4h057dcquu315dvhoo.apps.googleusercontent.com',
    iosBundleId: 'com.quuuuuuuuu.quuuuuuuuu',
  );
}
